on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Build
permissions:
  id-token: write
  contents: read
env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - os: ubuntu-latest
          vcpkg_triplet: x64-linux
        - os: windows-latest
          vcpkg_triplet: x64-windows
      fail-fast: false
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          submodules: recursive
      - uses: johnwason/vcpkg-action@v5
        with:
          pkgs: pkgconf gettext-libintl maddy jsoncpp curl curlpp sqlite3 sqlcipher sqlitecpp[sqlcipher] dbus
          triplet: ${{ matrix.config.vcpkg_triplet }}
          extra-args: "--allow-unsupported"
          cache-key: ${{ matrix.config.os }}
          token: ${{ github.token }}
      - uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
