on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Linux
permissions:
  id-token: write
  contents: read
env:
  BUILD_TYPE: Release
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - name: "Build on x64"
          os: ubuntu-latest
          env:
            CC: gcc
            CXX: g++
      fail-fast: false
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup Environment"
        run: |
          mkdir build
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
          sudo apt-get update
          sudo apt-get install g++-14 gcc-14 xdg-user-dirs gettext tzdata locales -y
          xdg-user-dirs-update
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
      - name: "Unlock Keyring"
        uses: t1m0thyj/unlock-keyring@v1
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: curl gettext-libintl glib gtest jsoncpp libsecret libuuid maddy openssl
          triplet: x64-linux
          cache-key: ${{ matrix.config.os }}
          revision: 59aeb8fe8fe1c980de6bd5ba634cf21024522d81
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
          cmake --build .
      - name: "Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install .
      - name: "Test"
        run: ${{github.workspace}}/build/libnick_test
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/install
          name: Linux-x64-${{env.BUILD_TYPE}}
