on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Windows
permissions:
  id-token: write
  contents: read
env:
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  build:
    name: "Build on x64"
    runs-on: windows-2019
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup Environment"
        run: mkdir build
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: curl gettext-libintl gtest jsoncpp maddy openssl
          triplet: x64-windows
          revision: b27651341123a59f7187b42ef2bc476284afb310
          token: ${{ secrets.GITHUB_TOKEN }}
          github-binarycache: true
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -G "Visual Studio 17 2022" .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
          cmake --build . --config Release
      - name: "Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install .
      - name: "Test"
        run: ${{github.workspace}}/build/Release/libnick_test.exe
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/install
          name: Windows-x64-${{env.BUILD_TYPE}}
